version: 2
updates:

# Maintain dependencies for GitHub Actions in dev branch
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev" 
