dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\product\product_division\alpha_product_division'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/product/product_division/alpha_product_division/config/alpha_product_division_config.json'
  base_table_name: 'alpha_product_division'

market_dag_list:
  - market_ext: 'abq'
  - market_ext: 'ash'
  - market_ext: 'atl'
  - market_ext: 'cfl'
  - market_ext: 'col'
  - market_ext: 'den'
  - market_ext: 'dfb'
  - market_ext: 'far'
  - market_ext: 'ind'
  - market_ext: 'jac'
  - market_ext: 'jes'
  - market_ext: 'laf'
  - market_ext: 'nor'
  - market_ext: 'okl'
  - market_ext: 'oma'
  - market_ext: 'pen'
  - market_ext: 'sav'
  - market_ext: 'sio'
  - market_ext: 'tam'
  - market_ext: 'wsd'

config_values:
  src_base_folder: 'alpha/product/inbound'
  sql_template_path: 'dags/raw/product/product_division/alpha_product_division/sf_sql'
  sf_schema: 'product'
  sf_hist_table: 'alpha_product_division_hist'
  sf_snap_table: 'alpha_product_division_snap'
  sf_hist_stream: 'alpha_product_division_hist_stream'
  market_src_files:
    market_file_abq: 'etl_prod_division.abq'
    market_file_ash: 'etl_prod_division.ash'
    market_file_atl: 'etl_prod_division.atl'
    market_file_cfl: 'etl_prod_division.cfl'
    market_file_col: 'etl_prod_division.col'
    market_file_den: 'etl_prod_division.den'
    market_file_dfb: 'etl_prod_division.dfb'
    market_file_far: 'etl_prod_division.far'
    market_file_ind: 'etl_prod_division.ind'
    market_file_jac: 'etl_prod_division.jac'
    market_file_jes: 'etl_prod_division.jes'
    market_file_laf: 'etl_prod_division.laf'
    market_file_nor: 'etl_prod_division.nor'
    market_file_okl: 'etl_prod_division.okl'
    market_file_oma: 'etl_prod_division.oma'
    market_file_pen: 'etl_prod_division.pen'
    market_file_sav: 'etl_prod_division.sav'
    market_file_sio: 'etl_prod_division.sio'
    market_file_tam: 'etl_prod_division.tam'
    market_file_wsd: 'etl_prod_division.wsd'
