dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\product\product_division\as400hi_product_division'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/product/product_division/as400hi_product_division/config/as400hi_product_division_config.json'
  base_table_name: 'as400hi_product_division'

market_dag_list:
  - market_ext: 'haw'
  - market_ext: 'kau'
  - market_ext: 'mau'
  - market_ext: 'oah'

config_values:
  src_base_folder: 'as400hi/product/inbound'
  sql_template_path: 'dags/raw/product/product_division/as400hi_product_division/sf_sql'
  sf_schema: 'product'
  sf_hist_table: 'as400hi_product_division_hist'
  sf_snap_table: 'as400hi_product_division_snap'
  sf_hist_stream: 'as400hi_product_division_hist_stream'
  market_src_files:
    market_file_haw: 'etl_prod_division.haw'
    market_file_kau: 'etl_prod_division.kau'
    market_file_mau: 'etl_prod_division.mau'
    market_file_oah: 'etl_prod_division.oah'
