dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\customer\customer_type\corporate_alpha_customer_type'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/customer/customer_type/corporate_alpha_customer_type/config/corporate_alpha_customer_type_config.json'
  base_table_name: 'corporate_alpha_customer_type'

market_dag_list:
  - market_ext: 'csv'

config_values:
  src_base_folder: 'alpha/customer/inbound'
  sql_template_path: 'dags/raw/customer/customer_type/corporate_alpha_customer_type/sf_sql'
  sf_schema: 'customer'
  sf_hist_table: 'corporate_alpha_customer_type_hist'
  sf_snap_table: 'corporate_alpha_customer_type_snap'
  sf_hist_stream: 'corporate_alpha_customer_type_hist_stream'
  market_src_files:
    market_file_csv: 'etl_customer_type.csv'