dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\product\product_division\hp3k_product_division'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/product/product_division/hp3k_product_division/config/hp3k_product_division_config.json'
  base_table_name: 'hp3k_product_division'

market_dag_list:
  - market_ext: 'bro'
  - market_ext: 'brs'
  - market_ext: 'liv'
  - market_ext: 'lvs'

config_values:
  src_base_folder: 'hp3k/product/inbound'
  sql_template_path: 'dags/raw/product/product_division/hp3k_product_division/sf_sql'
  sf_schema: 'product'
  sf_hist_table: 'hp3k_product_division_hist'
  sf_snap_table: 'hp3k_product_division_snap'
  sf_hist_stream: 'hp3k_product_division_hist_stream'
  market_src_files:
    market_file_bro: 'etl_prod_division.bro'
    market_file_brs: 'etl_prod_division.brs'
    market_file_liv: 'etl_prod_division.liv'
    market_file_lvs: 'etl_prod_division.lvs'
