dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\product\product_division\opici_product_division'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/product/product_division/opici_product_division/config/opici_product_division_config.json'
  base_table_name: 'opici_product_division'

market_dag_list:
  - market_ext: 'nym'
  - market_ext: 'nyu'

config_values:
  src_base_folder: 'opici/product/inbound'
  sql_template_path: 'dags/raw/product/product_division/opici_product_division/sf_sql'
  sf_schema: 'product'
  sf_hist_table: 'opici_product_division_hist'
  sf_snap_table: 'opici_product_division_snap'
  sf_hist_stream: 'opici_product_division_hist_stream'
  market_src_files:
    market_file_nym: 'etl_prod_division.nym'
    market_file_nyu: 'etl_prod_division.nyu'
