dags_dir_path: 'C:\projects\de-snowflake-airflow-processing\dags\raw\product\product_division\vip_id_mt_product_division'

common_values:
  global_config_path: 'dags/raw/globalConfig.json'
  dag_config_path: 'dags/raw/product/product_division/vip_id_mt_product_division/config/vip_id_mt_product_division_config.json'
  base_table_name: 'vip_id_mt_product_division'

market_dag_list:
  - market_ext: 'ank'
  - market_ext: 'frb'
  - market_ext: 'sea'

config_values:
  src_base_folder: 'vip-id_mt/product/inbound'
  sql_template_path: 'dags/raw/product/product_division/vip_id_mt_product_division/sf_sql'
  sf_schema: 'product'
  sf_hist_table: 'vip_id_mt_product_division_hist'
  sf_snap_table: 'vip_id_mt_product_division_snap'
  sf_hist_stream: 'vip_id_mt_product_division_hist_stream'
  market_src_files:
    market_file_ank: 'etl_prod_division.ank'
    market_file_frb: 'etl_prod_division.frb'
    market_file_sea: 'etl_prod_division.sea'
